// Generated by CoffeeScript 1.9.3
(function() {
  exports.onComment = function(comment) {
    var name, ref;
    name = (ref = comment.ctx) != null ? ref.name : void 0;
    if ((name != null ? name.charAt(0) : void 0) === '_') {
      return comment.isPrivate = true;
    }
  };

}).call(this);
